[build]
builder = "nixpacks"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["jdk21_headless", "maven"]

[deploy]
startCommand = "java -Dserver.port=$PORT -jar target/*.jar --spring.profiles.active=prod"